INSERT INTO Allergy (allergen, symptoms, category) VALUES
-- Food allergens
('Balsam of Peru', 'Redness, swelling, itching, dermatitis reactions, stomatitis, cheilitis, pruritus, hand eczema, rhinitis, conjunctivitis, and blisters.', 'Food'),
('Buckwheat', 'Asthma, rhinitis, pruritus, gastrointestinal disturbances, urticaria, angioedema, shock, anaphylaxis', 'Food'),
('Celery', 'Abdominal pain, nausea, vomiting, oral allergy syndrome, urticaria, neck or facial swelling, severe asthma symptoms, exercise-induced anaphylaxis, potentially fatal anaphylactic shocks', 'Food'),
('Egg', 'Anaphylaxis, swelling, sometimes flatulence and vomiting', 'Food'),
('Fish', 'Respiratory reactions, anaphylaxis, oral allergy syndrome, sometimes vomiting', 'Food'),
('Fruit', 'Mild itching, rash, generalized urticaria, oral allergy syndrome, abdominal pain, vomiting, anaphylaxis', 'Food'),
('Garlic', 'Dermatitis, asymmetrical fissure', 'Food'),
('Oats', 'Dermatitis, respiratory problems, anaphylaxis', 'Food'),
('Maize', 'Hives, pallor, confusion, dizziness, stomach pain, swelling, vomiting, indigestion, diarrhea, cough, tightness in throat', 'Food'),
('Milk', 'Skin rash, hives, vomiting, diarrhea, constipation, stomach pain, flatulence, colitis, nasal congestion, dermatitis, blisters, migraine, anaphylaxis', 'Food'),
('Mustard', 'Eczema, rash, hives, facial swelling, other skin reactions, oral allergy syndrome, conjunctivitis', 'Food'),
('Peanut', 'Anaphylaxis and swelling, sometimes vomiting', 'Food'),
('Poultry Meat', 'Hives, swelling, nausea, vomiting, diarrhea, severe oral allergy syndrome, shortness of breath, rarely anaphylactic shock', 'Food'),
('Red Meat', 'Hives, swelling, dermatitis, stomach pain, nausea, vomiting, dizziness, fainting, shortness of breath, anaphylaxis', 'Food'),
('Rice', 'Sneezing, runny nose, itching, stomachache, eczema.', 'Food'),
('Sesame', 'Possible respiratory, skin, and gastrointestinal reactions which can trigger serious systemic anaphylactic responses.', 'Food'),
('Shellfish', 'Respiratory symptoms, anaphylaxis, oral allergy syndrome, gastrointestinal symptoms, rhinitis, conjunctivitis', 'Food'),
('Soy', 'Anaphylaxis, asthma exacerbation, rhinitis, allergic conjunctivitis, hives, atopic dermatitis, swelling, diarrhea, nausea, vomiting', 'Food'),
('Sulfites', 'Hives, rash, redness of skin, headache, burning behind eyes, asthma-like breathing difficulties, anaphylaxis', 'Food'),
('Tartrazine', 'Skin irritation, hives, rash', 'Food'),
('Tree nut', 'Anaphylaxis, swelling, rash, hives, sometimes vomiting', 'Food'),
('Wheat', 'Eczema, hives, asthma, hay fever, oral allergy syndrome, angioedema, abdominal cramps, celiac disease, exercise-induced anaphylaxis', 'Food'),
-- Medical allergens
('Tetracycline', 'Severe headache, dizziness, blurred vision, fever, chills, body aches, flu symptoms, dark colored urine', 'Medical'),
('Dilantin', 'Swollen glands, easy bruising or bleeding, fever, sore throat', 'Medical'),
('Tegretol', 'Shortness of breath, wheezing or difficulty breathing, swelling of the face, lips, tongue, hives', 'Medical'),
('Penicillin', 'Diarrhea, hypersensitivity, nausea, rash, neurotoxicity, urticaria', 'Medical'),
('Cephalosporins', 'Maculopapular, serum-sickness–like reactions, and anaphylaxis.', 'Medical'),
('Sulfonamides', 'Urinary tract disorders, haemopoietic disorder, Stevens–Johnson syndrome', 'Medical'),
('Non-steroidal anti-inflammatories', 'Swollen eyes, lips, or tongue, difficulty swallowing', 'Medical'),
('Intravenous contrast dye', 'Anaphylactoid reactions and contrast-induced nephropathy', 'Medical'),
('Local anesthetics', 'Urticaria and rash, dyspnea, wheezing, flushing, cyanosis, tachycardia', 'Medical'),
-- Environmental allergens
('Pollen', 'Sneezing, irritation of the nose, nasal congestion, minor fatigue', 'Environmental'),
('Cat', 'Sneezing, itchy swollen eyes, rash, congestion, wheezing', 'Environmental'),
('Dog', 'Rash, sneezing, congestion, wheezing, vomiting from coughing, itchy welts.', 'Environmental'),
('Insect sting', 'Hives, wheezing, possible anaphylaxis', 'Environmental'),
('Mold', 'Sneeze, coughing, itchy, discharge from the nose, respiratory irritation, congested feeling', 'Environmental'),
('Perfume', 'Itchy eyes, runny nose, sore throat, headaches, muscle/joint pain, asthma attack', 'Environmental'),
('Cosmetics', 'Contact dermatitis, irritant contact dermatitis, conjunctivitis, sneezing', 'Environmental'),
('Semen', 'Burning, pain and swelling, swelling or blisters, vaginal redness, fever, runny nose, extreme fatigue', 'Environmental'),
('Latex', 'Contact dermatitis, hypersensitivity', 'Environmental'),
('Water', 'Epidermal itching, swelling of the oral cavity after drinking water, anaphylaxis', 'Environmental'),
('Cold stimuli', 'Hives, itching', 'Environmental'),
('House dust mite', 'Asthma', 'Environmental'),
('Nickel', 'Allergic contact dermatitis, dyshidrotic eczema', 'Environmental'),
('Gold', 'Allergic contact dermatitis', 'Environmental'),
('Chromium', 'Allergic contact dermatitis', 'Environmental'),
('Cobalt chloride', 'Allergic contact dermatitis', 'Environmental'),
('Formaldehyde', 'Allergic contact dermatitis', 'Environmental'),
('Photographic developers', 'Allergic contact dermatitis', 'Environmental'),
('Fungicide', 'Allergic contact dermatitis, fever, anaphylaxis', 'Environmental'),
-- Contact allergens
('Dimethylaminopropylamine (DMAPA)', 'Eyelid dermatitis', 'Contact'),
('Latex', 'Ethylene-ripened fruits, allergic contact dermatitis, hypersensitivity', 'Contact'),
('Paraphenylenediamine (PPD)', 'Eyelid dermatitis, black hair dye, color developer, scuba gear, henna', 'Contact'),
('Glyceryl monothioglycolate', 'Eyelid dermatitis, permanent hair waving solutions', 'Contact'),
('Toluenesulfonamide formaldehyde', 'Eyelid dermatitis, nail polish', 'Contact'),
('Tennis ball felt waterproofing agent (Nano Titanium dioxide)', 'Weight gain in middle-aged subjects, physical contact in hypersensitive patients only', 'Contact');


-- Change the manager later
INSERT INTO Department (name) VALUES
('Emergency'),
('Anaesthetics'),
('Surgery'),
('Laboratory'),
('Pediatrics'),
('Neurology'),
('Ophthalmology'),
('Otorhinolaryngology'),
('Cardiology'),
('Gastroenterology'),
('Gynaecology'),
('Orthopedics');


INSERT INTO Shift (day_of_week, start_hour, end_hour) VALUES
('MON', '06:00:00', '14:00:00'),
('MON', '14:00:00', '22:00:00'),
('MON', '22:00:00', '06:00:00'),
('TUE', '06:00:00', '14:00:00'),
('TUE', '14:00:00', '22:00:00'),
('TUE', '22:00:00', '06:00:00'),
('WED', '06:00:00', '14:00:00'),
('WED', '14:00:00', '22:00:00'),
('WED', '22:00:00', '06:00:00'),
('THU', '06:00:00', '14:00:00'),
('THU', '14:00:00', '22:00:00'),
('THU', '22:00:00', '06:00:00'),
('FRI', '06:00:00', '14:00:00'),
('FRI', '14:00:00', '22:00:00'),
('FRI', '22:00:00', '06:00:00'),
('SAT', '06:00:00', '14:00:00'),
('SAT', '14:00:00', '22:00:00'),
('SAT', '22:00:00', '06:00:00'),
('SUN', '06:00:00', '14:00:00'),
('SUN', '14:00:00', '22:00:00'),
('SUN', '22:00:00', '06:00:00');


INSERT INTO Medicine (name, effect, side_effect, quantity, price) VALUES
-- Emergency
('Epinephrine', 'Treatment of severe allergic reactions, cardiac arrest', 'Palpitations, anxiety', 50, 25.00),
('Atropine', 'Treatment of bradycardia, poisoning', 'Dry mouth, blurred vision', 75, 15.00),
('Naloxone', 'Reverses opioid overdose', 'Rapid heart rate, sweating', 60, 18.00),
-- Anaesthetics
('Propofol', 'Induces and maintains anesthesia', 'Low blood pressure, respiratory depression', 40, 50.00),
('Lidocaine', 'Local anesthetic', 'Dizziness, numbness', 80, 12.00),
('Fentanyl', 'Pain relief, anesthetic adjunct', 'Nausea, respiratory depression', 45, 75.00),
-- Surgery
('Cefazolin', 'Prevents infection during surgery', 'Allergic reactions, diarrhea', 90, 20.00),
('Heparin', 'Prevents blood clots during surgery', 'Bleeding, thrombocytopenia', 70, 30.00),
('Ketamine', 'Induction of anesthesia, pain relief', 'Hallucinations, hypertension', 30, 40.00),
-- Laboratory
('Glucose', 'Blood sugar regulation', 'Hyperglycemia in high doses', 100, 5.00),
('Saline', 'Fluid replacement', 'Overhydration', 200, 2.50),
('Potassium chloride', 'Electrolyte replenishment', 'Hyperkalemia', 85, 10.00),
-- Pediatrics
('Amoxicillin', 'Treats bacterial infections', 'Rash, diarrhea', 120, 8.00),
('Ibuprofen (Pediatric)', 'Pain relief, fever reducer', 'Stomach upset, kidney damage', 110, 6.00),
('Diphenhydramine', 'Allergy relief, sleep aid', 'Drowsiness, dry mouth', 130, 7.50),
-- Neurology
('Diazepam', 'Anxiety relief, muscle relaxation', 'Drowsiness, dizziness', 95, 20.00),
('Carbamazepine', 'Treats seizures, neuropathic pain', 'Dizziness, nausea', 75, 22.00),
('Levetiracetam', 'Seizure prevention', 'Fatigue, mood changes', 65, 25.00),
-- Ophthalmology
('Timolol', 'Reduces intraocular pressure', 'Burning sensation, blurred vision', 50, 15.00),
('Atropine (Ophthalmic)', 'Dilates pupils', 'Dry mouth, blurred vision', 70, 12.00),
('Prednisolone acetate', 'Reduces eye inflammation', 'Increased eye pressure', 45, 18.00),
-- Otorhinolaryngology
('Fluticasone nasal spray', 'Reduces nasal inflammation', 'Nosebleeds, throat irritation', 100, 10.00),
('Cetirizine', 'Allergy relief', 'Drowsiness, dry mouth', 90, 8.00),
('Amoxicillin-clavulanate', 'Treats ENT infections', 'Diarrhea, rash', 110, 14.00),
-- Cardiology
('Atenolol', 'Reduces blood pressure, treats angina', 'Bradycardia, fatigue', 80, 20.00),
('Lisinopril', 'Lowers blood pressure, treats heart failure', 'Cough, hyperkalemia', 70, 18.00),
('Clopidogrel', 'Prevents blood clots', 'Bleeding, rash', 65, 25.00),
-- Gastroenterology
('Omeprazole', 'Reduces stomach acid', 'Headache, diarrhea', 150, 12.00),
('Metoclopramide', 'Treats nausea, GERD', 'Drowsiness, restlessness', 100, 10.00),
('Lactulose', 'Treats constipation, hepatic encephalopathy', 'Bloating, diarrhea', 90, 15.00),
-- Gynaecology
('Estradiol', 'Hormone replacement therapy', 'Breast tenderness, nausea', 85, 25.00),
('Medroxyprogesterone', 'Prevents endometrial hyperplasia', 'Weight gain, mood changes', 75, 20.00),
('Clomiphene', 'Treats infertility', 'Hot flashes, ovarian enlargement', 60, 30.00),
-- Orthopedics
('Methocarbamol', 'Muscle relaxation', 'Drowsiness, dizziness', 100, 18.00),
('Alendronate', 'Treats osteoporosis', 'Esophageal irritation, muscle pain', 70, 25.00),
('Naproxen', 'Pain relief, anti-inflammatory', 'Stomach ulcers, kidney damage', 120, 12.00),
-- Additional Medicines
('Aspirin', 'Pain relief, anti-inflammatory, fever reducer', 'Gastric irritation, bleeding', 100, 5.00),
('Paracetamol', 'Pain relief, fever reducer', 'Liver damage in high doses', 200, 3.50),
('Ibuprofen', 'Pain relief, anti-inflammatory, fever reducer', 'Stomach ulcers, kidney damage', 150, 4.20),
('Hydrocortisone', 'Reduces inflammation', 'Weight gain, mood changes', 50, 10.00),
('Warfarin', 'Prevents blood clots', 'Bleeding, bruising', 80, 22.00),
('Clindamycin', 'Treats bacterial infections', 'Diarrhea, nausea', 90, 15.00),
('Dexamethasone', 'Reduces inflammation', 'Increased appetite, weight gain', 60, 18.00),
('Gentamicin', 'Treats serious bacterial infections', 'Kidney damage, hearing loss', 50, 30.00),
('Tetracycline', 'Treats bacterial infections', 'Photosensitivity, nausea', 100, 12.00),
('Morphine', 'Pain relief', 'Respiratory depression, nausea', 30, 35.00),
('Furosemide', 'Diuretic, reduces fluid buildup', 'Dehydration, electrolyte imbalance', 120, 8.00),
('Verapamil', 'Treats high blood pressure, angina', 'Constipation, dizziness', 75, 22.00),
('Losartan', 'Lowers blood pressure', 'Dizziness, increased potassium levels', 80, 20.00),
('Spironolactone', 'Diuretic, treats heart failure', 'Hyperkalemia, breast tenderness', 70, 25.00),
('Digoxin', 'Treats heart failure, arrhythmias', 'Nausea, dizziness', 60, 28.00),
('Nitroglycerin', 'Treats angina', 'Headache, dizziness', 50, 18.00),
('Ceftriaxone', 'Treats bacterial infections', 'Diarrhea, rash', 80, 20.00),
('Hydrochlorothiazide', 'Diuretic, treats high blood pressure', 'Low potassium, dizziness', 90, 10.00),
('Simvastatin', 'Lowers cholesterol', 'Muscle pain, liver damage', 85, 15.00),
('Metformin', 'Treats type 2 diabetes', 'Nausea, diarrhea', 120, 12.00),
('Insulin', 'Lowers blood sugar levels', 'Hypoglycemia, weight gain', 60, 35.00),
('Salbutamol', 'Bronchodilator, treats asthma', 'Tremor, palpitations', 100, 10.00),
('Montelukast', 'Treats asthma, allergies', 'Headache, abdominal pain', 90, 15.00),
('Ranitidine', 'Reduces stomach acid', 'Headache, dizziness', 75, 10.00),
('Azithromycin', 'Treats bacterial infections', 'Diarrhea, nausea', 110, 20.00),
('Clotrimazole', 'Treats fungal infections', 'Skin irritation, rash', 100, 8.00);
